FROM python:3.12
WORKDIR /app

RUN pip install --no-cache-dir llama_cpp_python==0.3.8
COPY requirements-cpu.txt requirements-base.txt .
RUN pip install --no-cache-dir -r requirements-cpu.txt

COPY app.py .
COPY utils.py .
COPY config.py .

EXPOSE 7860
CMD ["python3", "app.py"]