FROM python:3.10
WORKDIR /app
RUN pip install --no-cache-dir llama_cpp_python==0.2.88
COPY requirements-cpu.txt requirements-base.txt .
RUN pip install --no-cache-dir -r requirements-cpu.txt
COPY app.py config.py utils.py .
EXPOSE 7860
CMD ["python3", "app.py"]
