FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel AS builder

ENV CUDA_DOCKER_ARCH=all
ENV GGML_CUDA=1
ENV CMAKE_ARGS="-DGGML_CUDA=on"

COPY requirements-base.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels llama_cpp_python==0.2.88 && \
    pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements-base.txt

FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime
WORKDIR /app

COPY --from=builder /app/wheels /wheels
RUN pip install --no-cache-dir /wheels/*

COPY app.py config.py utils.py .

EXPOSE 7860
CMD ["python3", "app.py"]
