ARG CUDA_IMAGE=12.9.1-runtime-ubuntu24.04
FROM nvcr.io/nvidia/cuda:${CUDA_IMAGE}

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-pip libgomp1 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

COPY wheels /wheels
RUN pip install --no-cache-dir --break-system-packages /wheels/* && rm -rf /wheels

WORKDIR /app
COPY modules modules
COPY tests modules
COPY app.py config.py .

ENV GRADIO_SERVER_NAME=0.0.0.0
EXPOSE 7860

CMD ["python3", "app.py"]