name: Build and Push Docker (CUDA only)

on: workflow_dispatch

permissions:
  contents: write
  packages: write

jobs:
  # build-and-push-builder:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Check disk usage
  #       run: df -h

  #     - name: Build and push image builder
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: Dockerfile-cuda-nvidia-builder
  #         push: true
  #         # pull: true
  #         platforms: linux/amd64
  #         tags: |
  #           ghcr.io/sergey21000/chatbot-rag:${{ github.ref_name }}-builder-cuda
  #         # build-args: |
  #           # BUILDKIT_INLINE_CACHE=1

  #     - name: Check disk usage
  #       run: df -h

  build-and-push-final:
    runs-on: ubuntu-24.04
    # needs: build-and-push-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check disk usage
        run: df -h

      - name: Build and push final image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-cuda-nvidia-final
          push: true
          # pull: true
          platforms: linux/amd64
          tags: |
            ghcr.io/sergey21000/chatbot-rag:${{ github.ref_name }}-cuda
          build-args: |
            BUILDER_TAG=${{ github.ref_name }}-builder-cuda
            # BUILDKIT_INLINE_CACHE=1

      - name: Check disk usage
        run: df -h

