name: Build and Push Docker (CPU only)

on: workflow_dispatch

permissions:
  contents: write
  packages: write

jobs:
  docker-cpu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CPU image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile-cpu
          push: true
          pull: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-cpu