name: Test Unstructured

on: workflow_dispatch

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-magic
      - name: Show installed packages
        run: pip freeze
      - name: Test import
        run: python -c "import magic; print('Imported OK')"
